version: "3.9"
services:
	mysql:
		image: mysql:8.0
		environment:
			MYSQL_ROOT_PASSWORD: root
			MYSQL_DATABASE: rally_db
			MYSQL_USER: rally_user
			MYSQL_PASSWORD: secret
		ports:
			- "3306:3306"
		volumes:
			- db_data:/var/lib/mysql
			- ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
		restart: unless-stopped

volumes:
	db_data: