-- Users table (stores Discord users)
CREATE TABLE IF NOT EXISTS users (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	discord_id BIGINT UNSIGNED NOT NULL UNIQUE,
	username VARCHAR(100) NOT NULL,
	discriminator VARCHAR(10) NULL,
	avatar VARCHAR(255) NULL,
	email VARCHAR(190) NULL,
	created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Guilds the app knows about
CREATE TABLE IF NOT EXISTS guilds (
	id BIGINT UNSIGNED PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	icon VARCHAR(255) NULL,
	created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Channels known to the app (subset)
CREATE TABLE IF NOT EXISTS channels (
	id BIGINT UNSIGNED PRIMARY KEY,
	guild_id BIGINT UNSIGNED NOT NULL,
	name VARCHAR(200) NOT NULL,
	created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	INDEX (guild_id),
	FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Rallies
CREATE TABLE IF NOT EXISTS rallies (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	guild_id BIGINT UNSIGNED NOT NULL,
	channel_id BIGINT UNSIGNED NOT NULL,
	creator_discord_id BIGINT UNSIGNED NOT NULL,
	name VARCHAR(255) NOT NULL,
	prep_seconds INT UNSIGNED NOT NULL,
	attacker_travel_seconds INT UNSIGNED NOT NULL,
	your_travel_seconds INT UNSIGNED NOT NULL,
	safety_buffer_seconds INT UNSIGNED NOT NULL,
	mention_target VARCHAR(255) NULL,
	status ENUM('pending','scheduled','completed','cancelled') NOT NULL DEFAULT 'pending',
	created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	-- Computed fields for scheduling (UTC)
	send_at DATETIME NOT NULL,
	prealert_at DATETIME NULL,
	INDEX (guild_id),
	INDEX (channel_id),
	INDEX (creator_discord_id),
	INDEX (status),
	INDEX (send_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Reinforcements assignments
CREATE TABLE IF NOT EXISTS reinforcements (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	rally_id BIGINT UNSIGNED NOT NULL,
	assignee_discord_id BIGINT UNSIGNED NOT NULL,
	role VARCHAR(100) NULL,
	notes VARCHAR(255) NULL,
	created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	INDEX (rally_id),
	FOREIGN KEY (rally_id) REFERENCES rallies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Alerts log (optional)
CREATE TABLE IF NOT EXISTS alerts (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	rally_id BIGINT UNSIGNED NOT NULL,
	type ENUM('prealert','main') NOT NULL,
	scheduled_at DATETIME NOT NULL,
	sent_at DATETIME NULL,
	payload TEXT NULL,
	created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	INDEX (rally_id),
	FOREIGN KEY (rally_id) REFERENCES rallies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;